-- Drop and recreate all DB for a truly clean slate

DROP DATABASE IF EXISTS BASE_STAGING;
DROP DATABASE IF EXISTS BASE_WORK;
DROP DATABASE IF EXISTS BASE_SOCLE;
DROP DATABASE IF  EXISTS BASE_TECHNIQUE;
