CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_patient_age_by_pathology AS
SELECT 
    c.PATH_DSC AS pathology,
    DATEDIFF(year, i.BIRT_DT, c.CONS_STRT_DTTM) AS age_at_consultation,
    c.CONS_STRT_DTTM AS consultation_date
FROM BASE_SOCLE.PUBLIC.CONSULTATION c
JOIN BASE_SOCLE.PUBLIC.INDIVIDUAL i 
    ON c.PATN_ID = i.PART_ID
WHERE c.PATH_DSC IS NOT NULL
AND i.BIRT_DT IS NOT NULL;
