CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_avg_age_by_pathology AS
SELECT 
    c.PATH_DSC AS pathology,
    AVG(DATEDIFF(year, i.BIRT_DT, CURRENT_DATE)) AS avg_age
FROM BASE_SOCLE.PUBLIC.INDIVIDUAL i
JOIN BASE_SOCLE.PUBLIC.CONSULTATION c
    ON i.PART_ID = c.PATN_ID
WHERE c.PATH_DSC IS NOT NULL
GROUP BY c.PATH_DSC;
