CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_doctor_pathology_period AS
SELECT 
    c.PATH_DSC AS pathology,
    s.PART_ID AS doctor_id,
    c.CONS_STRT_DTTM AS consultation_date
FROM BASE_SOCLE.PUBLIC.CONSULTATION c
JOIN BASE_SOCLE.PUBLIC.STAFF s 
    ON c.STFF_ID = s.PART_ID
WHERE c.PATH_DSC IS NOT NULL;
