CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_room_occupancy_status AS
SELECT 
    r.ROOM_NUM,
    CASE 
        WHEN h.ROOM_NUM IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS is_occupied,
    h.HOSP_STRT_DTTM AS start_date,
    h.HOSP_END_DTTM AS end_date
FROM BASE_SOCLE.PUBLIC.ROOM r
LEFT JOIN BASE_SOCLE.PUBLIC.HOSPITALIZATION h
    ON r.ROOM_NUM = h.ROOM_NUM;
