CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_empty_rooms AS
SELECT r.ROOM_NUM
FROM BASE_SOCLE.PUBLIC.ROOM r
WHERE r.ROOM_NUM NOT IN (
    SELECT DISTINCT h.ROOM_NUM
    FROM BASE_SOCLE.PUBLIC.HOSPITALIZATION h
    WHERE h.HOSP_STRT_DTTM BETWEEN '2023-01-01' AND '2023-12-31'
);
