CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_hospital_stays AS
SELECT 
    h.CONS_ID,
    h.HOSP_STRT_DTTM AS start_date,
    h.HOSP_END_DTTM AS end_date,
    DATEDIFF(day, h.HOSP_STRT_DTTM, h.HOSP_END_DTTM) AS duration_days
FROM BASE_SOCLE.PUBLIC.HOSPITALIZATION h;
