CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_patients_one_night AS
SELECT 
    COUNT(DISTINCT h.CONS_ID) AS total_stays,
    COUNT(DISTINCT CASE 
        WHEN DATEDIFF(day, h.HOSP_STRT_DTTM, h.HOSP_END_DTTM) >= 1 THEN h.CONS_ID 
    END) AS stays_one_night_or_more
FROM BASE_SOCLE.PUBLIC.HOSPITALIZATION h;
