CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_rooms_with_pathology AS
SELECT 
    h.ROOM_NUM,
    c.PATH_DSC AS pathology,
    h.HOSP_STRT_DTTM AS start_date,
    h.HOSP_END_DTTM AS end_date
FROM BASE_SOCLE.PUBLIC.HOSPITALIZATION h
JOIN BASE_SOCLE.PUBLIC.CONSULTATION c 
    ON h.CONS_ID = c.CONS_ID
WHERE c.PATH_DSC IS NOT NULL;
