CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_rooms_by_pathology AS
SELECT 
    c.PATH_DSC AS pathology,
    COUNT(DISTINCT h.ROOM_NUM) AS num_rooms
FROM BASE_SOCLE.PUBLIC.HOSPITALIZATION h
JOIN BASE_SOCLE.PUBLIC.CONSULTATION c 
    ON h.CONS_ID = c.CONS_ID
WHERE c.PATH_DSC IS NOT NULL
GROUP BY c.PATH_DSC;
