CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_medication_by_pathology AS
SELECT 
    c.PATH_DSC AS pathology,
    t.MEDC_ID AS medication_id,
    t.MEDC_QTY AS quantity,
    t.TRET_CRTN_DTTM AS prescription_date
FROM BASE_SOCLE.PUBLIC.TREATMENT t
JOIN BASE_SOCLE.PUBLIC.CONSULTATION c 
    ON t.CONS_ID = c.CONS_ID
WHERE c.PATH_DSC IS NOT NULL;
