CREATE OR REPLACE VIEW BASE_SOCLE.PUBLIC.vw_top_medication_by_pathology AS
SELECT 
    c.PATH_DSC AS pathology,
    t.MEDC_ID AS medication_id,
    SUM(t.MEDC_QTY) AS total_quantity
FROM BASE_SOCLE.PUBLIC.TREATMENT t
JOIN BASE_SOCLE.PUBLIC.CONSULTATION c 
    ON t.CONS_ID = c.CONS_ID
WHERE c.PATH_DSC IS NOT NULL
GROUP BY c.PATH_DSC, t.MEDC_ID
QUALIFY RANK() OVER (PARTITION BY c.PATH_DSC ORDER BY SUM(t.MEDC_QTY) DESC) = 1;
