INSERT INTO BASE_SOCLE.PUBLIC.INDIVIDUAL (
    PART_ID, INDV_NAME, INDV_FIRS_NAME, INDV_STTS_CD, CRTN_DTTM,
    UPDT_DTTM, BIRT_DT, BIRT_CITY, BIRT_CNTR, SOCL_NUM, EXEC_ID
)
SELECT
    PART_ID, INDV_NAME, INDV_FIRS_NAME, INDV_STTS_CD, CRTN_DTTM,
    UPDT_DTTM, BIRT_DT, BIRT_CITY, BIRT_CNTR, SOCL_NUM, %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.O_INDV;
