INSERT INTO BASE_SOCLE.PUBLIC.STAFF (
    PART_ID, WORK_STRT_DTTM, WORK_END_DTTM, WORK_END_RESN, EXEC_ID
)
SELECT
    PART_ID, WORK_STRT_DTTM, WORK_END_DTTM, WORK_END_RESN, %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.O_STFF;
