INSERT INTO BASE_SOCLE.PUBLIC.MEDICINE (MEDC_ID, MEDC_CD, MEDC_NAME, MEDC_COND, MEDC_CATG, MANF_BRND, EXEC_ID)
SELECT MEDC_ID, MEDC_CD, MEDC_NAME, MEDC_COND, MEDC_CATG, MANF_BRND, %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.R_MEDC;
