INSERT INTO BASE_SOCLE.PUBLIC.CONSULTATION (
    CONS_ID, STFF_ID, PATN_ID, CONS_STRT_DTTM, CONS_END_DTTM,
    PATN_WEGH, PATN_TEMP, TEMP_UNIT, BLD_PRSS, PATH_DSC, DIBT_IND, HOSP_IND, EXEC_ID
)
SELECT
    CONS_ID, STFF_ID, PATN_ID, CONS_STRT_DTTM, CONS_END_DTTM,
    PATN_WEGH, PATN_TEMP, TEMP_UNIT, BLD_PRSS, PATH_DSC, DIBT_IND, HOSP_IND, %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.O_CONS;
