INSERT INTO BASE_SOCLE.PUBLIC.HOSPITALIZATION (
    HOSP_ID, CONS_ID, ROOM_NUM, HOSP_STRT_DTTM, HOSP_END_DTTM,
    HOSP_FINL_RATE, STFF_ID, EXEC_ID
)
SELECT
    HOSP_ID, CONS_ID, ROOM_NUM, HOSP_STRT_DTTM, HOSP_END_DTTM,
    HOSP_FINL_RATE, STFF_ID, %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.O_HOSP;
