INSERT INTO BASE_SOCLE.PUBLIC.TELEPHONE (PART_ID, CNTR_IND, TELP_NUM, STRT_VALD_DTTM, END_VALD_DTTM, EXEC_ID)
SELECT PART_ID, CNTR_IND, TELP_NUM, STRT_VALD_DTTM, END_VALD_DTTM,  %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.O_TELP;
