INSERT INTO BASE_SOCLE.PUBLIC.ADDRESS (
    PART_ID, STRT_NUM, STRT_DSC, COMP_STRT, POST_CD, CITY_NAME, CNTR_NAME,
    STRT_VALD_DTTM, END_VALD_DTTM, EXEC_ID
)
SELECT
    PART_ID, STRT_NUM, STRT_DSC, COMP_STRT, POST_CD, CITY_NAME, CNTR_NAME,
    STRT_VALD_DTTM, END_VALD_DTTM, %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.O_ADDR;
