INSERT INTO BASE_SOCLE.PUBLIC.TREATMENT (
    TRET_ID, MEDC_ID, MEDC_QTY, DOSG_DSC, CONS_ID, TRET_CRTN_DTTM, EXEC_ID
)
SELECT TRET_ID, MEDC_ID, MEDC_QTY, DOSG_DSC, CONS_ID, TRET_CRTN_DTTM,  %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.O_TRET;
