INSERT INTO BASE_SOCLE.PUBLIC.ROOM (ROOM_NUM, ROOM_NAME, FLOR_NUM, BULD_NAME, ROOM_TYP, ROOM_DAY_RATE, CRTN_DT, EXEC_ID)
SELECT ROOM_NUM, ROOM_NAME, FLOR_NUM, BULD_NAME, ROOM_TYP, ROOM_DAY_RATE, CRTN_DT, %s AS EXEC_ID
FROM BASE_WORK.PUBLIC.R_ROOM;
