-- /!\ Necessite la création préalable de la table R_PART dans BASE_WORK /!\

INSERT INTO BASE_WORK.PUBLIC.O_CONS (
    CONS_ID,
    STFF_ID,
    PATN_ID,
    CONS_STRT_DTTM,
    CONS_END_DTTM,
    PATN_WEGH,
    PATN_TEMP,
    TEMP_UNIT,
    BLD_PRSS,
    PATH_DSC,
    DIBT_IND,
    TRET_ID,
    HOSP_IND,
    EXEC_ID
)
SELECT
    c.ID_CONSULT AS CONS_ID,
    rp_stff.PART_ID AS STFF_ID,
    rp_patn.PART_ID AS PATN_ID,
    c.TS_DEBUT_CONSULT AS CONS_STRT_DTTM,
    c.TS_FIN_CONSULT AS CONS_END_DTTM,
    c.POIDS_PATIENT AS PATN_WEGH,
    c.TEMP_PATIENT AS PATN_TEMP,
    c.UNIT_TEMP AS TEMP_UNIT,
    c.TENSION_PATIENT AS BLD_PRSS,
    c.DSC_PATHO AS PATH_DSC,
    CASE WHEN c.INDIC_DIABETE = 'True' THEN 1 ELSE 0 END AS DIBT_IND,
    c.ID_TRAITEMENT AS TRET_ID,
    CASE WHEN c.INDIC_HOSPI = 'True' THEN 1 ELSE 0 END AS HOSP_IND,
    %s AS EXEC_ID
FROM BASE_STAGING.PUBLIC.CONSULTATION c
LEFT JOIN BASE_WORK.PUBLIC.R_PART rp_stff
    ON c.ID_PERSONNEL = rp_stff.SRC_ID
   AND rp_stff.SRC_TYP <> 'Patient'
LEFT JOIN BASE_WORK.PUBLIC.R_PART rp_patn
    ON c.ID_PATIENT = rp_patn.SRC_ID
   AND rp_patn.SRC_TYP = 'Patient';
