INSERT INTO BASE_WORK.O_CONS (
    CONS_ID,
    CONS_STRT_DTTM,
    CONS_END_DTTM,
    PATN_WEGH,
    PATN_TEMP,
    TEMP_UNIT,
    BLD_PRSS,
    PATH_DSC,
    TRET_ID
)
SELECT
    ID_CONSULT AS CONS_ID,
    TS_DEBUT_CONSULT AS CONS_STRT_DTTM,
    TS_FIN_CONSULT AS CONS_END_DTTM,
    POIDS_PATIENT AS PATN_WEGH,
    TEMP_PATIENT AS PATN_TEMP,
    UNIT_TEMP AS TEMP_UNIT,
    TENSION_PATIENT AS BLD_PRSS,
    DSC_PATHO AS PATH_DSC,
    ID_TRAITEMENT AS TRET_ID
FROM BASE_STAGING.CONSULTATION;
