-- /!\ Necessite la création préalable de la table R_PART dans BASE_WORK /!\
INSERT INTO BASE_WORK.O_STFF (
    PART_ID,
    WORK_STRT_DTTM,
    WORK_END_DTTM,
    WORK_END_RESN
)
SELECT
    rp.PART_ID,
    p.TS_DEBUT_ACTIVITE AS WORK_STRT_DTTM,
    p.TS_FIN_ACTIVITE AS WORK_END_DTTM,
    p.RAISON_FIN_ACTIVITE AS WORK_END_RESN
FROM BASE_STAGING.PERSONNEL p
JOIN BASE_WORK.R_PART rp
  ON p.ID_PERSONNEL = rp.SRC_ID
 AND p.FONCTION_PERSONNEL = rp.SRC_TYP;

