INSERT INTO BASE_WORK.O_HOSP (
    HOSP_ID,
    CONS_ID,
    ROOM_NUM,
    HOSP_STRT_DTTM,
    HOSP_END_DTTM,
    HOSP_FINL_RATE
)
SELECT
    ID_HOSPI AS HOSP_ID,
    ID_CONSULT AS CONS_ID,
    NO_CHAMBRE AS ROOM_NUM,
    TS_DEBUT_HOSPI AS HOSP_STRT_DTTM,
    TS_FIN_HOSPI AS HOSP_END_DTTM,
    COUT_HOSPI AS HOSP_FINL_RATE
FROM BASE_STAGING.HOSPITALISATION;
