INSERT INTO BASE_WORK.PUBLIC.R_MEDC (
    MEDC_ID,
    MEDC_CD,
    MEDC_NAME,
    MEDC_COND,
    MEDC_CATG,
    MANF_BRND,
    EXEC_ID
)
SELECT
    MEDC_ID,
    CD_MEDICAMENT,
    NOM_MEDICAMENT,
    CONDIT_MEDICAMENT,
    CATG_MEDICAMENT,
    MARQUE_FABRI,
    %s AS EXEC_ID
FROM (
    WITH medic_unique AS (
        SELECT
            CD_MEDICAMENT,
            NOM_MEDICAMENT,
            CONDIT_MEDICAMENT,
            CATG_MEDICAMENT,
            MARQUE_FABRI,
            DENSE_RANK() OVER (
                ORDER BY CD_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI
            ) AS MEDC_ID
        FROM BASE_STAGING.PUBLIC.MEDICAMENT
    )
    SELECT *
    FROM medic_unique
) AS medc_final;
