INSERT INTO BASE_WORK.O_ADDR (
    STRT_NUM,
    STRT_DSC,
    COMP_STRT,
    POST_CD,
    CITY_NAME,
    CNTR_NAME,
    STRT_VALD_DTTM,
    END_VALD_DTTM
)
SELECT
    NUM_VOIE AS STRT_NUM,
    DSC_VOIE AS STRT_DSC,
    CMPL_VOIE AS COMP_STRT,
    CD_POSTAL AS POST_CD,
    VILLE AS CITY_NAME,
    PAYS AS CNTR_NAME,
    TS_CREATION_PATIENT AS STRT_VALD_DTTM,
    TS_MAJ_PATIENT AS END_VALD_DTTM
FROM BASE_STAGING.PATIENT;
