-- /!\ Necessite la création préalable de la table R_PART dans BASE_WORK /!\

INSERT INTO BASE_WORK.O_INDV (
    PART_ID,
    INDV_NAME,
    INDV_FIRS_NAME,
    INDV_STTS_CD,
    CRTN_DTTM,
    UPDT_DTTM,
    BIRT_DT,
    BIRT_CITY,
    BIRT_CNTR,
    SOCL_NUM
)
SELECT
    rp.PART_ID,
    p.NOM_PERSONNEL AS INDV_NAME,
    p.PRENOM_PERSONNEL AS INDV_FIRS_NAME,
    p.CD_STATUT_PERSONNEL AS INDV_STTS_CD,
    p.TS_CREATION_PERSONNEL AS CRTN_DTTM,
    p.TS_MAJ_PERSONNEL AS UPDT_DTTM,
    p.DT_NAISS AS BIRT_DT,
    p.VILLE_NAISS AS BIRT_CITY,
    p.PAYS_NAISS AS BIRT_CNTR,
    p.NUM_SECU AS SOCL_NUM
FROM BASE_STAGING.PERSONNEL p
JOIN BASE_WORK.R_PART rp -- Jointure pour récupérer PART_ID 
  ON p.ID_PERSONNEL = rp.SRC_ID
 AND p.FONCTION_PERSONNEL = rp.SRC_TYP;

