-- /!\ Necessite la création préalable de la table R_PART dans BASE_WORK /!\

INSERT INTO BASE_WORK.O_TELP (
    PART_ID,
    CNTR_IND,
    TELP_NUM,
    STRT_VALD_DTTM,
    END_VALD_DTTM
)
SELECT
    rp.PART_ID,
    p.IND_PAYS_NUM_TELP AS CNTR_IND,
    p.NUM_TELEPHONE AS TELP_NUM,
    p.TS_CREATION_PATIENT AS STRT_VALD_DTTM,
    p.TS_MAJ_PATIENT AS END_VALD_DTTM
FROM BASE_STAGING.PATIENT p
JOIN BASE_WORK.R_PART rp
  ON p.ID_PATIENT = rp.SRC_ID
 AND rp.SRC_TYP = 'Patient';

