INSERT INTO BASE_WORK.O_TRET (
    TRET_ID,
    MEDC_QTY,
    DOSG_DSC,
    CONS_ID,
    TRET_CRTN_DTTM
)
SELECT
    ID_TRAITEMENT AS TRET_ID,
    QTE_MEDICAMENT AS MEDC_QTY,
    DSC_POSOLOGIE AS DOSG_DSC,
    ID_CONSULT AS CONS_ID,
    TS_CREATION_TRAITEMENT AS TRET_CRTN_DTTM
FROM BASE_STAGING.TRAITEMENT;
