-- /!\ Executer ce code après le fichier _insert_r_medc.sql /!\

INSERT INTO BASE_WORK.O_TRET (
    TRET_ID,
    MEDC_ID,
    MEDC_QTY,
    DOSG_DSC,
    CONS_ID,
    TRET_CRTN_DTTM, 
    EXEC_ID
)
SELECT
    t.ID_TRAITEMENT AS TRET_ID,
    m.MEDC_ID,
    t.QTE_MEDICAMENT AS MEDC_QTY,
    t.DSC_POSOLOGIE AS DOSG_DSC,
    t.ID_CONSULT AS CONS_ID,
    t.TS_CREATION_TRAITEMENT AS TRET_CRTN_DTTM,
    %s AS EXEC_ID
FROM BASE_STAGING.TRAITEMENT t
JOIN BASE_WORK.R_MEDC m -- Jointure nécéssaire pour récupérer MEDC_ID
    ON t.CD_MEDICAMENT = m.CD_MEDICAMENT
   AND t.CATG_MEDICAMENT = m.CATG_MEDICAMENT
   AND t.MARQUE_FABRI = m.MARQUE_FABRI;

