-- /!\ Necessite la création préalable de la table R_PART dans BASE_WORK /!\

INSERT INTO BASE_WORK.O_ADDR (
    PART_ID,
    STRT_NUM,
    STRT_DSC,
    COMP_STRT,
    POST_CD,
    CITY_NAME,
    CNTR_NAME,
    STRT_VALD_DTTM,
    END_VALD_DTTM
)
SELECT
    rp.PART_ID,
    p.NUM_VOIE AS STRT_NUM,
    p.DSC_VOIE AS STRT_DSC,
    p.CMPL_VOIE AS COMP_STRT,
    p.CD_POSTAL AS POST_CD,
    p.VILLE AS CITY_NAME,
    p.PAYS AS CNTR_NAME,
    p.TS_CREATION_PATIENT AS STRT_VALD_DTTM,
    p.TS_MAJ_PATIENT AS END_VALD_DTTM
FROM BASE_STAGING.PATIENT p
JOIN BASE_WORK.R_PART rp
  ON p.ID_PATIENT = rp.SRC_ID
 AND rp.SRC_TYP = 'Patient';

