INSERT INTO BASE_WORK.PUBLIC.R_MEDC (
    MEDC_ID,
    MEDC_CD,
    MEDC_NAME,
    MEDC_COND,
    MEDC_CATG,
    MANF_BRND,
    EXEC_ID
)
SELECT
    DENSE_RANK() OVER (ORDER BY CD_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI) AS MEDC_ID,
    CD_MEDICAMENT,
    NOM_MEDICAMENT,
    CONDIT_MEDICAMENT,
    CATG_MEDICAMENT,
    MARQUE_FABRI,
    %s AS EXEC_ID
FROM (
    SELECT DISTINCT
        CD_MEDICAMENT,
        NOM_MEDICAMENT,
        CONDIT_MEDICAMENT,
        CATG_MEDICAMENT,
        MARQUE_FABRI
    FROM BASE_STAGING.PUBLIC.MEDICAMENT
) AS medic_unique;
