INSERT INTO BASE_WORK.PUBLIC.O_INDV (
    PART_ID,
    INDV_NAME,
    INDV_FIRS_NAME,
    INDV_STTS_CD,
    CRTN_DTTM,
    UPDT_DTTM,
    BIRT_DT,
    BIRT_CITY,
    BIRT_CNTR,
    SOCL_NUM,
    EXEC_ID
)
SELECT DISTINCT
    rp.PART_ID,
    p.NOM_PERSONNEL AS INDV_NAME,
    p.PRENOM_PERSONNEL AS INDV_FIRS_NAME,
    p.CD_STATUT_PERSONNEL AS INDV_STTS_CD,
    p.TS_CREATION_PERSONNEL AS CRTN_DTTM,
    p.TS_CREATION_PERSONNEL AS UPDT_DTTM, --! Remplacer par TS_MAJ_PERSONNEL si disponible
    NULL AS BIRT_DT,
    NULL AS BIRT_CITY,
    NULL AS BIRT_CNTR,
    NULL AS SOCL_NUM,
    %s AS EXEC_ID
FROM BASE_STAGING.PUBLIC.PERSONNEL p
JOIN BASE_WORK.PUBLIC.R_PART rp
  ON p.ID_PERSONNEL = rp.SRC_ID
 AND p.FONCTION_PERSONNEL = rp.SRC_TYP

UNION ALL

SELECT DISTINCT
    rp.PART_ID,
    p.NOM_PATIENT AS INDV_NAME,
    p.PRENOM_PATIENT AS INDV_FIRS_NAME,
    'Actif' AS INDV_STTS_CD,
    p.TS_CREATION_PATIENT AS CRTN_DTTM,
    p.TS_MAJ_PATIENT AS UPDT_DTTM,
    p.DT_NAISS AS BIRT_DT,
    p.VILLE_NAISS AS BIRT_CITY,
    p.PAYS_NAISS AS BIRT_CNTR,
    p.NUM_SECU AS SOCL_NUM,
    %s AS EXEC_ID
FROM BASE_STAGING.PUBLIC.PATIENT p
JOIN BASE_WORK.PUBLIC.R_PART rp
  ON p.ID_PATIENT = rp.SRC_ID
 AND rp.SRC_TYP = 'Patient';
