INSERT INTO BASE_WORK.O_INDV (
    INDV_NAME,
    INDV_FIRS_NAME,
    INDV_STTS_CD,
    CRTN_DTTM,
    UPDT_DTTM,
    INDV_NAME,
    INDV_FIRS_NAME,
    CRTN_DTTM,
    UPDT_DTTM,
    BIRT_DT,
    BIRT_CITY,
    BIRT_CNTR,
    SOCL_NUM
)
SELECT
    NOM_PERSONNEL AS INDV_NAME,
    PRENOM_PERSONNEL AS INDV_FIRS_NAME,
    CD_STATUT_PERSONNEL AS INDV_STTS_CD,
    TS_CREATION_PERSONNEL AS CRTN_DTTM,
    TS_MAJ_PERSONNEL AS UPDT_DTTM,
    NOM_PATIENT AS INDV_NAME,
    PRENOM_PATIENT AS INDV_FIRS_NAME,
    TS_CREATION_PATIENT AS CRTN_DTTM,
    TS_MAJ_PATIENT AS UPDT_DTTM,
    DT_NAISS AS BIRT_DT,
    VILLE_NAISS AS BIRT_CITY,
    PAYS_NAISS AS BIRT_CNTR,
    NUM_SECU AS SOCL_NUM
FROM BASE_STAGING.PERSONNEL;
