INSERT INTO BASE_WORK.O_TELP (
    CNTR_IND,
    TELP_NUM,
    STRT_VALD_DTTM,
    END_VALD_DTTM
)
SELECT
    IND_PAYS_NUM_TELP AS CNTR_IND,
    NUM_TELEPHONE AS TELP_NUM,
    TS_CREATION_PATIENT AS STRT_VALD_DTTM,
    TS_MAJ_PATIENT AS END_VALD_DTTM
FROM BASE_STAGING.PATIENT;
