-- /!\ Necessite la création préalable de la table R_PART dans BASE_WORK /!\

INSERT INTO BASE_WORK.PUBLIC.O_STFF (
    PART_ID,
    WORK_STRT_DTTM,
    WORK_END_DTTM,
    WORK_END_RESN,
    EXEC_ID
)
SELECT DISTINCT
    rp.PART_ID,
    p.TS_DEBUT_ACTIVITE AS WORK_STRT_DTTM,
    p.TS_FIN_ACTIVITE AS WORK_END_DTTM,
    p.RAISON_FIN_ACTIVITE AS WORK_END_RESN,
    %s AS EXEC_ID
FROM BASE_STAGING.PUBLIC.PERSONNEL p
JOIN BASE_WORK.PUBLIC.R_PART rp
  ON p.ID_PERSONNEL = rp.SRC_ID
 AND p.FONCTION_PERSONNEL = rp.SRC_TYP;
