INSERT INTO BASE_WORK.PUBLIC.O_TELP (
    PART_ID,
    CNTR_IND,
    TELP_NUM,
    STRT_VALD_DTTM,
    END_VALD_DTTM,
    EXEC_ID
)
SELECT DISTINCT
    rp.PART_ID,
    p.IND_PAYS_NUM_TELP AS CNTR_IND,
    p.NUM_TELEPHONE AS TELP_NUM,
    p.TS_CREATION_PATIENT AS STRT_VALD_DTTM,
    p.TS_MAJ_PATIENT AS END_VALD_DTTM,
    %s AS EXEC_ID
FROM BASE_STAGING.PUBLIC.PATIENT p
JOIN BASE_WORK.PUBLIC.R_PART rp
  ON p.ID_PATIENT = rp.SRC_ID
 AND rp.SRC_TYP = 'Patient';
