INSERT INTO BASE_WORK.R_ROOM (
    ROOM_NUM,
    ROOM_NAME,
    FLOR_NUM,
    BULD_NAME,
    ROOM_TYP,
    ROOM_DAY_RATE,
    CRTN_DT
)
SELECT
    NO_CHAMBRE AS ROOM_NUM,
    NOM_CHAMBRE AS ROOM_NAME,
    NO_ETAGE AS FLOR_NUM,
    NOM_BATIMENT AS BULD_NAME,
    TYPE_CHAMBRE AS ROOM_TYP,
    PRIX_JOUR AS ROOM_DAY_RATE,
    DT_CREATION AS CRTN_DT
FROM BASE_STAGING.CHAMBRE;
