WITH medic_unique AS (
    SELECT
        CD_MEDICAMENT,
        NOM_MEDICAMENT,
        CONDIT_MEDICAMENT,
        CATG_MEDICAMENT,
        MARQUE_FABRI,
        DENSE_RANK() OVER (ORDER BY CD_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI) AS MEDC_ID
    FROM BASE_STAGING.MEDICAMENT
)
INSERT INTO BASE_WORK.R_MEDC (
    MEDC_ID,
    MEDC_CD,
    MEDC_NAME,
    MEDC_COND,
    MEDC_CATG,
    MANF_BRND
)
SELECT
    MEDC_ID,
    CD_MEDICAMENT,
    NOM_MEDICAMENT,
    CONDIT_MEDICAMENT,
    CATG_MEDICAMENT,
    MARQUE_FABRI
FROM medic_unique;
