INSERT INTO BASE_WORK.PUBLIC.O_HOSP (
    HOSP_ID,
    CONS_ID,
    ROOM_NUM,
    HOSP_STRT_DTTM,
    HOSP_END_DTTM,
    HOSP_FINL_RATE,
    STFF_ID,
    EXEC_ID
)
SELECT DISTINCT
    h.ID_HOSPI AS HOSP_ID,
    h.ID_CONSULT_HOSPI AS CONS_ID,
    h.NO_CHAMBRE_HOSPI AS ROOM_NUM,
    h.TS_DEBUT_HOSPI AS HOSP_STRT_DTTM,
    h.TS_FIN_HOSPI AS HOSP_END_DTTM,
    h.COUT_HOSPI AS HOSP_FINL_RATE,
    rp.PART_ID AS STFF_ID,
    %s AS EXEC_ID
FROM BASE_STAGING.PUBLIC.HOSPITALISATION h
LEFT JOIN BASE_WORK.PUBLIC.R_PART rp
    ON h.ID_PERSONNEL_RESP = rp.SRC_ID
   AND rp.SRC_TYP <> 'Patient';
