INSERT INTO BASE_WORK.O_STFF (
    WORK_STRT_DTTM,
    WORK_END_DTTM,
    WORK_END_RESN
)
SELECT
    TS_DEBUT_ACTIVITE AS WORK_STRT_DTTM,
    TS_FIN_ACTIVITE AS WORK_END_DTTM,
    RAISON_FIN_ACTIVITE AS WORK_END_RESN
FROM BASE_STAGING.PERSONNEL;
