-- Script de création des bases de données du SID
-- Auteur : Nadia
-- Date : 29/05/2025



CREATE DATABASE IF NOT EXISTS BASE_SOCLE;
CREATE DATABASE IF NOT EXISTS BASE_TECHNIQUE;
CREATE DATABASE IF NOT EXISTS BASE_STAGING;
CREATE DATABASE IF NOT EXISTS BASE_WORK;
