--Dans une table de staging (couche intermédiaire pour ingérer/transformer les données), 
--il est rare et pas recommandé de mettre des contraintes strictes comme :

--PK (Primary Keys)

--FK (Foreign Keys)

--Contraintes NOT NULL trop sévères

--L'idée du staging, c'est d'accepter des données « brutes » ou imparfaites,
-- parfois incomplètes, pour ensuite les nettoyer, valider, enrichir, etc., 
--dans la couche suivante (par exemple la couche WRK ou ODS).

USE DATABASE BASE_STAGING;
USE SCHEMA PUBLIC;

-- TABLE CHAMBRE
DROP TABLE IF EXISTS CHAMBRE;
CREATE TABLE CHAMBRE (
    NO_CHAMBRE INTEGER NOT NULL,
    NOM_CHAMBRE VARCHAR(20) NOT NULL,
    NO_ETAGE INTEGER,
    NOM_BATIMENT VARCHAR(20),
    TYPE_CHAMBRE VARCHAR(10),
    PRIX_JOUR INTEGER NOT NULL,
    DT_CREATION DATE  NOT NULL
);

-- TABLE TRAITEMENT
DROP TABLE IF EXISTS TRAITEMENT;
CREATE TABLE TRAITEMENT (
    ID_TRAITEMENT INTEGER NOT NULL,
    CD_MEDICAMENT INTEGER NOT NULL,
    CATG_MEDICAMENT VARCHAR(100) NOT NULL,
    MARQUE_FABRI VARCHAR(100) NOT NULL,
    QTE_MEDICAMENT INTEGER,
    DSC_POSOLOGIE VARCHAR(100) NOT NULL,
    ID_CONSULT INTEGER NOT NULL,
    TS_CREATION_TRAITEMENT TIMESTAMP(0) NOT NULL
);

-- TABLE PERSONNEL
DROP TABLE IF EXISTS PERSONNEL;
CREATE TABLE PERSONNEL (
    ID_PERSONNEL INTEGER NOT NULL,
    NOM_PERSONNEL VARCHAR(100) NOT NULL,
    PRENOM_PERSONNEL VARCHAR(100) NOT NULL,
    FONCTION_PERSONNEL VARCHAR(50) NOT NULL,
    TS_DEBUT_ACTIVITE TIMESTAMP(0),
    TS_FIN_ACTIVITE TIMESTAMP(0),
    RAISON_FIN_ACTIVITE VARCHAR(100),
    TS_CREATION_PERSONNEL TIMESTAMP(0),
    TS_MAJ_PERSONNEL TIMESTAMP(0),
    CD_STATUT_PERSONNEL VARCHAR(10) NOT NULL
);

-- TABLE PATIENT
DROP TABLE IF EXISTS PATIENT;
CREATE TABLE PATIENT (
    ID_PATIENT INTEGER NOT NULL,
    NOM_PATIENT VARCHAR(100) NOT NULL,
    PRENOM_PATIENT VARCHAR(100) NOT NULL,
    DT_NAISS DATE,
    VILLE_NAISS VARCHAR(100),
    PAYS_NAISS VARCHAR(100),
    NUM_SECU VARCHAR(15),
    IND_PAYS_NUM_TELP VARCHAR(5),
    NUM_TELEPHONE VARCHAR(20),
    NUM_VOIE VARCHAR(10),
    DSC_VOIE VARCHAR(250),
    CMPL_VOIE VARCHAR(250),
    CD_POSTAL VARCHAR(10),
    VILLE VARCHAR(100),
    PAYS VARCHAR(100),
    TS_CREATION_PATIENT TIMESTAMP(0) NOT NULL,
    TS_MAJ_PATIENT TIMESTAMP(0) NOT NULL
);

-- TABLE CONSULTATION
DROP TABLE IF EXISTS CONSULTATION;
CREATE TABLE CONSULTATION (
    ID_CONSULT INTEGER NOT NULL,
    ID_PERSONNEL INTEGER NOT NULL,
    ID_PATIENT INTEGER NOT NULL,
    TS_DEBUT_CONSULT TIMESTAMP(0) NOT NULL,
    TS_FIN_CONSULT TIMESTAMP(0) NOT NULL,
    POIDS_PATIENT FLOAT NOT NULL,
    TEMP_PATIENT FLOAT,
    UNIT_TEMP VARCHAR(15),
    TENSION_PATIENT FLOAT,
    DSC_PATHO VARCHAR(250),
    INDIC_DIABETE BOOLEAN,
    INDIC_HOSPI BOOLEAN
);

-- TABLE HOSPITALISATION
DROP TABLE IF EXISTS HOSPITALISATION;
CREATE TABLE HOSPITALISATION (
    ID_HOSPI INTEGER NOT NULL,
    ID_CONSULT_hospi INTEGER NOT NULL,
    NO_CHAMBRE_hospi INTEGER NOT NULL,
    TS_DEBUT_HOSPI TIMESTAMP(0) NOT NULL,
    TS_FIN_HOSPI TIMESTAMP(0),
    COUT_HOSPI FLOAT, 
    ID_PERSONNEL_RESP INTEGER NOT NULL
);

-- TABLE MEDICAMENT
DROP TABLE IF EXISTS MEDICAMENT;
CREATE TABLE MEDICAMENT (
    CD_MEDICAMENT VARCHAR(10) NOT NULL,
    NOM_MEDICAMENT VARCHAR(250),
    CONDIT_MEDICAMENT VARCHAR(100),
    CATG_MEDICAMENT VARCHAR(100) NOT NULL,
    MARQUE_FABRI VARCHAR(100) NOT NULL
);
