USE DATABASE BASE_WORK;
USE SCHEMA PUBLIC;


-- R_PART
DROP TABLE IF EXISTS R_PART;

CREATE TABLE R_PART (
    PART_ID INTEGER NOT NULL,
    SRC_ID INTEGER NOT NULL,
    SRC_TYP VARCHAR(50) NOT NULL
);


-- R_ROOM
DROP TABLE IF EXISTS R_ROOM;

CREATE TABLE R_ROOM (
    ROOM_NUM INTEGER NOT NULL,
    ROOM_NAME VARCHAR(20) NOT NULL,
    FLOR_NUM INTEGER,
    BULD_NAME VARCHAR(20),
    ROOM_TYP VARCHAR(10),
    ROOM_DAY_RATE INTEGER NOT NULL,
    CRTN_DT DATE NOT NULL,
    EXEC_ID INTEGER NOT NULL
);


-- R_MEDC
DROP TABLE IF EXISTS R_MEDC;

CREATE TABLE R_MEDC (
    MEDC_ID INTEGER NOT NULL,
    MEDC_CD VARCHAR(10) NOT NULL,
    MEDC_NAME VARCHAR(250),
    MEDC_COND VARCHAR(100),
    MEDC_CATG VARCHAR(100) NOT NULL,
    MANF_BRND VARCHAR(100) NOT NULL,
    EXEC_ID INTEGER NOT NULL
);


-- O_INDV
DROP TABLE IF EXISTS O_INDV;

CREATE TABLE O_INDV (
    PART_ID INTEGER NOT NULL,
    INDV_NAME VARCHAR(100) NOT NULL,
    INDV_FIRS_NAME VARCHAR(100) NOT NULL,
    INDV_STTS_CD VARCHAR(10) NOT NULL,
    CRTN_DTTM TIMESTAMP(0) NOT NULL,
    UPDT_DTTM TIMESTAMP(0) NOT NULL,
    BIRT_DT DATE,
    BIRT_CITY VARCHAR(100),
    BIRT_CNTR VARCHAR(100),
    SOCL_NUM VARCHAR(15),
    EXEC_ID INTEGER NOT NULL
);


-- O_STFF
DROP TABLE IF EXISTS O_STFF;

CREATE TABLE O_STFF (
    PART_ID INTEGER NOT NULL,
    WORK_STRT_DTTM TIMESTAMP(0) NOT NULL,
    WORK_END_DTTM TIMESTAMP(0),
    WORK_END_RESN VARCHAR(100),
    EXEC_ID INTEGER NOT NULL
);


-- O_TELP
DROP TABLE IF EXISTS O_TELP;

CREATE TABLE O_TELP (
    PART_ID INTEGER NOT NULL,
    CNTR_IND VARCHAR(5),
    TELP_NUM VARCHAR(20) NOT NULL,
    STRT_VALD_DTTM TIMESTAMP(0) NOT NULL,
    END_VALD_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_ID INTEGER NOT NULL
);


-- O_ADDR
DROP TABLE IF EXISTS O_ADDR;

CREATE TABLE O_ADDR (
    PART_ID INTEGER NOT NULL,
    STRT_NUM VARCHAR(10) NOT NULL,
    STRT_DSC VARCHAR(250) NOT NULL,
    COMP_STRT VARCHAR(250),
    POST_CD VARCHAR(10) NOT NULL,
    CITY_NAME VARCHAR(100),
    CNTR_NAME VARCHAR(100),
    STRT_VALD_DTTM TIMESTAMP(0) NOT NULL,
    END_VALD_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_ID INTEGER NOT NULL
);




-- O_CONS
DROP TABLE IF EXISTS O_CONS;

CREATE TABLE O_CONS (
    CONS_ID INTEGER NOT NULL,
    STFF_ID INTEGER NOT NULL,
    PATN_ID INTEGER NOT NULL,
    TRET_ID INTEGER,
    CONS_STRT_DTTM TIMESTAMP(0) NOT NULL,
    CONS_END_DTTM TIMESTAMP(0) NOT NULL,
    PATN_WEGH FLOAT NOT NULL,
    PATN_TEMP FLOAT,
    TEMP_UNIT VARCHAR(15),
    BLD_PRSS FLOAT,
    PATH_DSC VARCHAR(250),
    DIBT_IND BOOLEAN,
    HOSP_IND BOOLEAN,
    EXEC_ID INTEGER NOT NULL
);


-- O_TRET
DROP TABLE IF EXISTS O_TRET;

CREATE TABLE O_TRET (
    TRET_ID INTEGER NOT NULL,
    MEDC_ID INTEGER NOT NULL,
    MEDC_QTY INTEGER,
    DOSG_DSC VARCHAR(100) NOT NULL,
    CONS_ID INTEGER NOT NULL,
    TRET_CRTN_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_ID INTEGER NOT NULL
);


-- O_HOSP
DROP TABLE IF EXISTS O_HOSP;

CREATE TABLE O_HOSP (
    HOSP_ID INTEGER NOT NULL,
    CONS_ID INTEGER NOT NULL,
    ROOM_NUM INTEGER NOT NULL,
    HOSP_STRT_DTTM TIMESTAMP(0) NOT NULL,
    HOSP_END_DTTM TIMESTAMP(0) NOT NULL,
    HOSP_FINL_RATE FLOAT NOT NULL,
    STFF_ID INTEGER NOT NULL,
    EXEC_ID INTEGER NOT NULL
);

